import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import "./globals.css";
import { Inter } from 'next/font/google'
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

/* font optimization : */
const inter = Inter({ subsets: ['latin'] });
/* 
A link preload tag will be injected into the header of selected lines across subsets
when the preload option is correct, which is the default setting */


/* metadata obj */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutprops{
  children : React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutprops) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ToastContainer theme="colored" position="top-center"/>
        <main>  {children} </main>
        <Footer/>
      </body>
    </html>
  );
}
